# Generated by Django 4.2.20 on 2025-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=150, verbose_name='Марка')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Серийный номер')),
                ('invent_number', models.CharField(max_length=150, verbose_name='Инвентарный номер')),
                ('year_of_manufacture', models.DateTimeField(verbose_name='Дата производства')),
                ('year_of_sale', models.DateTimeField(verbose_name='Дата продажи')),
                ('commissioning_date', models.DateTimeField(verbose_name='Дата ввода в эксплуатацию')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'cart_hardware',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CartLPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='Улица, строение')),
                ('index', models.CharField(max_length=10, verbose_name='Индекс')),
                ('zip', models.CharField(max_length=250, verbose_name='Область, край')),
                ('representative_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Представитель ЛПУ 1')),
                ('representative_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Представитель ЛПУ 2')),
                ('representative_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Представитель ЛПУ 3')),
                ('lpu', models.CharField(max_length=150, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'cart_lpu',
                'ordering': ('id',),
            },
        ),
    ]
