# Generated by Django 4.2.20 on 2025-04-29 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='Улица, строение')),
                ('index', models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс')),
                ('representative_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Представитель ЛПУ 1')),
                ('representative_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Представитель ЛПУ 2')),
                ('representative_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Представитель ЛПУ 3')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city', verbose_name='Город')),
                ('zip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'card_lpu',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CardHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=150, verbose_name='Марка')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Серийный номер')),
                ('invent_number', models.CharField(max_length=150, verbose_name='Инвентарный номер')),
                ('year_of_manufacture', models.CharField(max_length=10, verbose_name='Дата производства')),
                ('year_of_sale', models.CharField(max_length=10, verbose_name='Дата продажи')),
                ('commissioning_date', models.CharField(max_length=10, verbose_name='Дата ввода в эксплуатацию')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Производитель')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country', verbose_name='Страна')),
                ('lpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cardlpu', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'card_hardware',
                'ordering': ('id',),
            },
        ),
    ]
