# Generated by Django 4.2.20 on 2025-04-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlpu',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.info', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='carthardware',
            name='cauntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.info', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='carthardware',
            name='lpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cartlpu', verbose_name='Владелец'),
        ),
    ]
