# Generated by Django 4.2.20 on 2025-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhardware',
            name='invent_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Инвентарный номер'),
        ),
    ]
