# Generated by Django 4.2.20 on 2025-04-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act_technical', '0004_initial'),
        ('main', '0002_initial'),
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartHardware',
            new_name='CardHardware',
        ),
        migrations.RenameModel(
            old_name='CartLPU',
            new_name='CardLPU',
        ),
        migrations.AlterModelTable(
            name='cardhardware',
            table='card_hardware',
        ),
        migrations.AlterModelTable(
            name='cardlpu',
            table='card_lpu',
        ),
    ]
