# Generated by Django 4.2.20 on 2025-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_carthardware_cardhardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhardware',
            name='manufacturer',
            field=models.CharField(default=0, max_length=150, verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardhardware',
            name='commissioning_date',
            field=models.CharField(max_length=10, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='cardhardware',
            name='year_of_manufacture',
            field=models.CharField(max_length=10, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='cardhardware',
            name='year_of_sale',
            field=models.CharField(max_length=10, verbose_name='Дата продажи'),
        ),
    ]
