# Generated by Django 4.2.20 on 2025-04-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_city_country'),
        ('cards', '0004_cardhardware_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhardware',
            name='cauntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='cardlpu',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city', verbose_name='Город'),
        ),
    ]
