# Generated by Django 4.2.20 on 2025-04-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardhardware_cauntry_alter_cardlpu_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardhardware',
            old_name='cauntry',
            new_name='country',
        ),
    ]
