# Generated by Django 4.2.20 on 2025-04-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_cauntry_cardhardware_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlpu',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон'),
        ),
    ]
