# Generated by Django 4.2.20 on 2025-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, unique=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Информацию',
                'verbose_name_plural': 'Информация',
                'db_table': 'info',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'templates',
                'ordering': ('id',),
            },
        ),
    ]
