# Generated by Django 4.2.20 on 2025-04-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_city_country'),
        ('cards', '0005_alter_cardhardware_cauntry_alter_cardlpu_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
