# Generated by Django 4.2.20 on 2025-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Должность'),
        ),
    ]
