# Generated by Django 4.2.20 on 2025-05-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profcategory', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Проф-категория')),
            ],
            options={
                'verbose_name': 'Проф-категория',
                'verbose_name_plural': 'Проф-категории',
                'db_table': 'usercategory',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercategory', to='users.usercategory'),
        ),
    ]
