# Generated by Django 4.2.20 on 2025-05-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ('id',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelTable(
            name='notifications',
            table='notifications_notifications',
        ),
    ]
