# Generated by Django 4.2.20 on 2025-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('check_result', models.TextField(blank=True, null=True, verbose_name='Результат проверки')),
                ('probable_ause', models.TextField(blank=True, null=True, verbose_name='Вероятная причина')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Заключение')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Коментарии')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Акт техсостояния',
                'verbose_name_plural': 'Акты техсостояния',
                'db_table': 'actt',
                'ordering': ('id',),
            },
        ),
    ]
