# Generated by Django 4.2.20 on 2025-04-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act_technical', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actt',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Акт техсостояния', 'verbose_name_plural': 'Акты техсостояния'},
        ),
        migrations.RenameField(
            model_name='actt',
            old_name='probable_ause',
            new_name='probable_cause',
        ),
    ]
