# Generated by Django 4.2.20 on 2025-04-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_manager', '0001_initial'),
        ('cards', '0001_initial'),
        ('act_technical', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actt',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='image_manager.location'),
        ),
        migrations.AddField(
            model_name='actt',
            name='lpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cartlpu', verbose_name='Владелец'),
        ),
    ]
