# Generated by Django 4.2.20 on 2025-05-05 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("act_technical", "0003_alter_actt_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actt",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
