# Generated by Django 4.2.20 on 2025-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("act_technical", "0005_commentsactt"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentsactt",
            name="created_at",
            field=models.DateField(auto_now=True, verbose_name="Дата коммента"),
        ),
    ]
