# Generated by Django 4.2.20 on 2025-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("act_technical", "0006_commentsactt_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsactt",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата коммента"),
        ),
    ]
