# Generated by Django 4.2.20 on 2025-05-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("act_technical", "0007_alter_commentsactt_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="act_images/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="act_technical.actt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение акта",
                "verbose_name_plural": "Изображения актов",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
